name: openpiv
channels:
  - damianavila82
  - conda-forge
dependencies:
- numpy>=1.8
- scipy>=0.14
- matplotlib>=1.2
- cython>=0.24.1
- qutip>=4.2.0
- bokeh
- rise
- hide_code
- plotly
- ply
- mpi4py
- deap
- psutil
- pandas
- matplotlib
- ipython
- notebook
- msgpack-python
- cython